server:
  port: 8001
mybatis:
  type-aliases-package: com.esoon.springcloud.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/DB-01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xrc1995109
